name: Build and Test
on:
    push:
        branches:
            - "renovate/**"
    pull_request:
        branches:
            - main
jobs:
    buildTest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
              with:
                  node-version-file: ".nvmrc"
                  cache: pnpm

            - run: pnpm i
            - run: pnpm run test
            - run: pnpm build
