name: Build and Test
on:
    push:
        branches:
            - "renovate/**"
    pull_request:
        branches:
            - main
jobs:
    buildTest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
            - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
              with:
                  node-version: "20"
            - run: yarn
            - run: yarn test
            - run: yarn build
