name: Build and Test
on:
    push:
        branches:
            - "renovate/**"
    pull_request:
        branches:
            - main
jobs:
    buildTest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
              with:
                  node-version-file: ".nvmrc"
                  cache: pnpm

            - run: pnpm i
            - run: pnpm run test
            - run: pnpm build
