name: PublishToNpm
on:
    push:
        branches:
            - main
            - release/*
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
              with:
                  node-version-file: ".nvmrc"
                  cache: pnpm
            - run: pnpm install --frozen-lockfile
            - run: pnpm test
            - run: pnpm build
            - name: Release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: npx semantic-release
