name: PublishToNpm
on:
    push:
        branches:
            - main
            - feature/*
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
              with:
                  node-version-file: ".nvmrc"
                  cache: pnpm
            - run: pnpm install
            - run: pnpm test
            - run: pnpm build
            - name: Release
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: npx semantic-release
